"""Write the base-vs-tuned comparison as Markdown from two evaluation folders.

    uv run python -m offscript_training.report training/runs/baseline training/runs/sft-v1/eval \\
        > training/runs/REPORT.md
"""

import json
import sys
from pathlib import Path

ROUTES = ("AI", "SEARCH", "HUMAN")


def _pct(value) -> str:
    return "—" if value is None else f"{value * 100:.0f}%"


def _confusion(block: dict) -> list[str]:
    lines = ["| Correct ↓ / predicted → | AI | SEARCH | HUMAN | invalid |", "|---|---|---|---|---|"]
    for gold in ROUTES:
        row = block["confusion"].get(gold, {})
        cells = [str(row.get(name, 0)) for name in (*ROUTES, "INVALID")]
        lines.append(f"| {gold} | " + " | ".join(cells) + " |")
    return lines


def render(base: dict, tuned: dict) -> str:
    b, t = base["all"], tuned["all"]
    rows = [
        ("Routing accuracy", _pct(b["accuracy"]), _pct(t["accuracy"])),
        ("Correct", f"{b['correct']}/{b['questions']}", f"{t['correct']}/{t['questions']}"),
        ("HUMAN precision", _pct(b["human_precision"]), _pct(t["human_precision"])),
        ("HUMAN recall", _pct(b["human_recall"]), _pct(t["human_recall"])),
        (
            "Inappropriate HUMAN referrals",
            b["inappropriate_human_referrals"],
            t["inappropriate_human_referrals"],
        ),
        ("Invalid outputs", b["invalid_outputs"], t["invalid_outputs"]),
    ]
    for kind in sorted(set(base["by_kind"]) | set(tuned["by_kind"])):
        rows.append(
            (
                f"Accuracy on {kind} questions",
                _pct(base["by_kind"].get(kind, {}).get("accuracy")),
                _pct(tuned["by_kind"].get(kind, {}).get("accuracy")),
            )
        )
    bc, tc = base["content"], tuned["content"]
    rows += [
        ("AI answer words (average)", bc["ai_answer_words_avg"], tc["ai_answer_words_avg"]),
        (
            "AI answers within target length",
            _pct(bc["ai_answers_within_target"]),
            _pct(tc["ai_answers_within_target"]),
        ),
        (
            "HUMAN questions within target length",
            _pct(bc["human_questions_within_target"]),
            _pct(tc["human_questions_within_target"]),
        ),
        (
            "Content-rule problems",
            sum(bc["content_rule_problems"].values()),
            sum(tc["content_rule_problems"].values()),
        ),
    ]
    if "steps" in base and "steps" in tuned:
        bs, ts = base["steps"]["all"], tuned["steps"]["all"]
        rows += [
            (
                "Missed steps (a step was expected)",
                f"{bs['missed_steps']}/{bs['expected_step']} ({_pct(bs['missed_step_rate'])})",
                f"{ts['missed_steps']}/{ts['expected_step']} ({_pct(ts['missed_step_rate'])})",
            ),
            (
                "False steps (no step was expected)",
                f"{bs['false_steps']}/{bs['expected_none']} ({_pct(bs['false_step_rate'])})",
                f"{ts['false_steps']}/{ts['expected_none']} ({_pct(ts['false_step_rate'])})",
            ),
        ]
    if "test_sealed_v2" in tuned["data"]:
        sealed_note = (
            "- The v2 sealed set was written in the same session as the v2 data review, after"
            " reading the training data; near-copies were checked (similarity < 0.8)."
        )
    else:
        sealed_note = (
            "- The sealed test set was written by the model-side author after reading the training"
            " questions; near-duplicates were checked (similarity < 0.6)."
        )
    lines = [
        "# Router evaluation: base vs fine-tuned",
        "",
        f"- Base: `{base['model']}`",
        f"- Tuned: `{tuned['model']}`",
        f"- Data: `{tuned['data']}`; router prompt version `{tuned['router_prompt_version']}`;"
        f" temperature {tuned['sampling']['temperature']} for both",
        "",
        "| Metric | Base | Tuned |",
        "|---|---|---|",
        *[f"| {name} | {old} | {new} |" for name, old, new in rows],
        "",
        "## Confusion: base",
        "",
        *_confusion(b),
        "",
        "## Confusion: tuned",
        "",
        *_confusion(t),
        "",
        "## Caveats",
        "",
        f"- Small test set ({t['questions']} questions), single run each: a difference of one or"
        " two questions is within noise.",
        "- The tuned checkpoint was chosen by validation loss (held-out training rows) before any"
        " sealed-set evaluation; no other checkpoint was evaluated on the sealed set.",
        sealed_note,
        "- Training content was generated by the base model, filtered by rules and corrected"
        " in review.",
        "- Content quality beyond these rules (correctness of answers) is not scored here.",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 1
    base, tuned = (json.loads((Path(folder) / "metrics.json").read_text()) for folder in argv)
    sys.stdout.write(render(base, tuned))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
