# ruff: noqa: E501  (text data: long strings are intentional)
REASONS = {
    1: "Why plants need light is settled biology that can be explained directly.",
    2: "The difference between mass and weight is basic physics that doesn't change.",
    3: "Why ice floats is a stable science fact, so it can be answered directly.",
    4: "Day and night come from Earth's rotation, a fact that never changes.",
    5: "Percentage change is a fixed formula that can be explained right away.",
    6: "What a median means is standard statistics, so a direct explanation works.",
    7: "Using a book's index is a general skill that works the same for any book.",
    8: "Making a simple budget is a general method that works for anyone.",
    9: "Password advice is well-established know-how that doesn't need a live check.",
    10: "The warning signs of phishing are well known and can be explained directly.",
    11: "How two-factor authentication works is stable know-how.",
    12: "Good backup habits are general practice that applies to any files.",
    13: "Summarising an article is a writing skill that can be explained directly.",
    14: "Writing a polite reminder is a general writing skill.",
    15: "Declining politely is everyday etiquette that can be explained directly.",
    16: "Asking for clarification is a general communication skill.",
    17: "Spaced repetition is a well-established study method.",
    18: "Breaking a big task down is a general planning method.",
    19: "Comparing options fairly is a general decision method.",
    20: "Proofreading is a general writing skill with well-known steps.",
    21: "Tracking deadlines is a general planning habit anyone can use.",
    22: "What a rain percentage means is a fixed definition, not today's forecast.",
    23: "What an algorithm is can be explained directly in simple words.",
    24: "Seasons come from Earth's tilt, a stable fact of astronomy.",
    25: "How sound travels is basic physics that can be explained directly.",
    26: "The difference between evaporation and boiling is basic science.",
    27: "How mirrors reflect is basic optics that can be explained directly.",
    28: "Checking your own understanding is a general study technique.",
    29: "Giving useful feedback is a general communication skill.",
    30: "How debit and credit cards differ in general is stable knowledge.",
    31: "Checking soil moisture is practical know-how you can use right away.",
    32: "Why shadows change length is basic astronomy you can see for yourself.",
    33: "Condensation on a cold glass is everyday physics.",
    34: "What makes an echo audible is basic sound physics.",
    35: "Comparing friction is a simple science method that works anywhere.",
    36: "Keeping a growth log is a general observation method.",
    37: "Learning bird sounds starts with general listening techniques.",
    38: "Noticing change over time is a general observation habit.",
    39: "Why reflections change with angle is basic optics.",
    40: "Reading the wind from grass or leaves is simple practical know-how.",
    41: "Asking to borrow a mat politely is general class etiquette.",
    42: "A gentle warm-up routine is general running know-how.",
    43: "Starting a quick sketch from life is a general drawing technique.",
    44: "Beginner birdwatching manners are the same in any park.",
    45: "Framing a building is a general phone-photography technique.",
    46: "Reading a trail sign follows the same checks on any trail.",
    47: "Watching pollinators respectfully is general nature-watching know-how.",
    48: "Introducing yourself at a first meet-up is general etiquette.",
    49: "Keeping a nature journal is a simple, general method.",
    50: "Introducing yourself to a coordinator is general volunteering etiquette.",
    51: "Orienting a map is a standard navigation skill.",
    52: "Asking about ingredients clearly is general food-safety know-how.",
    53: "Taking turns at a public table follows general etiquette.",
    54: "Basic fielding drills are general practice that works on any ground.",
    55: "Approaching a first class follows general beginner etiquette.",
    56: "Ordering at a busy stall follows simple, general etiquette.",
    57: "Safe litter-picking is general safety know-how.",
    58: "Noticing details on a walk is a general observation habit.",
    59: "Preparing for a first library visit follows general steps.",
    60: "Asking to join a volunteer session follows general etiquette.",
    61: "Observing the moon's phase is basic astronomy you can do anywhere.",
    62: "Settling nerves before a short reading is general public-speaking know-how.",
    63: "Listening closely on a walk is a simple, general practice.",
    64: "Sketching a tree starts with general drawing steps.",
    65: "Asking for directions politely is everyday etiquette.",
    66: "A short outdoor drawing exercise is general practice.",
    67: "Easing into a busy market follows general first-visit tips.",
    68: "Photographing street art respectfully follows general etiquette.",
    69: "Preparing for a group walk is general know-how.",
    70: "Asking to borrow shared equipment follows general etiquette.",
    71: "Comparing two places fairly is a general method.",
    72: "Starting a casual conversation is a general social skill.",
    73: "Weekend opening hours can change, so a current official listing is needed.",
    74: "Today's closing time can change, so it needs the museum's current listing.",
    75: "Weekly closing days can change, so a current listing is needed.",
    76: "Tomorrow's opening time should come from the museum's current listing.",
    77: "Accessible entrances can change with works, so current information is needed.",
    78: "Wheelchair availability today needs the museum's current information.",
    79: "Ticket prices change, so a current official price is needed.",
    80: "Entry fees and weekend rules can change, so a current listing is needed.",
    81: "Walk meeting points are set by organisers and can change week to week.",
    82: "This week's events are only known from current listings.",
    83: "Market dates are announced by organisers, so a current listing is needed.",
    84: "This weekend's walks are only known from current listings.",
    85: "Start points are set by the organiser and can change for each run.",
    86: "Workshop dates are announced by organisers, so a current listing is needed.",
    87: "Festival dates change every year, so a current announcement is needed.",
    88: "Public sky-watching sessions are scheduled month to month.",
    89: "Clean-up locations are announced by organisers for each event.",
    90: "Whether a reading is on this Friday needs a current listing.",
    91: "Court hours can change, so current public hours are needed.",
    92: "Open session times are set by the ground and can change.",
    93: "Booking rules for public courts can change, so current rules are needed.",
    94: "Last-train times can change, so the official timetable is needed.",
    95: "Ferries depend on weather and notices, so tomorrow's status needs a current source.",
    96: "Tonight's last bus needs the current timetable.",
    97: "Tomorrow's rain depends on the latest forecast.",
    98: "Air quality changes hour to hour, so today's official reading is needed.",
    99: "Heat warnings are issued daily, so the current advisory is needed.",
    100: "Trail access can change with weather and repairs, so current information is needed.",
    101: "Public hours can change, so a current listing is needed.",
    102: "Event closures are announced day to day, so a current notice is needed.",
    103: "Market days and hours can change, so a current listing is needed.",
    104: "This weekend's swaps are only known from current listings.",
    105: "Drop-in sessions are scheduled by each studio and can change.",
    106: "Library hours vary by branch and can change, so current hours are needed.",
    107: "Tournament winners change with each edition, so a current result is needed.",
    108: "Yesterday's score is a recent result that needs a current source.",
    109: "League standings change after every match.",
    110: "The latest winner changes every year, so a current result is needed.",
    111: "Office holders change, so the current chairperson needs an official source.",
    112: "Office holders change, so the current head needs an official source.",
    113: "Who holds the post can change, so a current official source is needed.",
    114: "The sitting MP can change after elections, so a current source is needed.",
    115: "Exchange rates move every day, so today's rate is needed.",
    116: "Fuel prices are revised often, so today's price is needed.",
    117: "The repo rate changes at RBI policy meetings, so the latest figure is needed.",
    118: "Tax rates can be revised, so the current official rate is needed.",
    119: "Application deadlines are set each year, so this year's notice is needed.",
    120: "Enrollment windows change every term, so the current notice is needed.",
    121: "Correction windows open and close on announced dates, so a current notice is needed.",
    122: "Result dates are announced by the university, so a current notice is needed.",
    123: "Tomorrow's weather depends on the latest forecast.",
    124: "The current temperature changes through the day.",
    125: "Cyclone alerts are issued as storms develop, so the latest bulletin is needed.",
    126: "Air quality changes hour to hour, so a current reading is needed.",
    127: "Train delays change through the day, so a live update is needed.",
    128: "First-train timings can change, so the current timetable is needed.",
    129: "Live service status needs a current official update.",
    130: "Government fees can be revised, so the current official fee is needed.",
    131: "Whether a rule changed this semester needs the institute's current notice.",
    132: "Required documents can change, so the current official list is needed.",
    133: "Outages are live events, so the current status page is needed.",
    134: "New Python versions come out regularly, so the latest one needs a current source.",
    135: "This week's security updates are only known from recent announcements.",
    136: "Official match rules are best checked against the federation's own source.",
    137: "Traditional dish lists vary by region, so a reliable source beats memory.",
    138: "Concert line-ups are best checked against a reliable music source.",
    139: "Regulars at the stall know what people here actually buy.",
    140: "How bargaining works at this market is local practice that shoppers know.",
    141: "Regular shoppers know which stall here is reliable for seasonal fruit.",
    142: "Vendors know their own closing routine firsthand.",
    143: "People who come every weekend know when this bazaar is quietest.",
    144: "Regulars know what's worth ordering at this cafe.",
    145: "Returning customers know which option this stall does best.",
    146: "People who eat here often can tell you how hot the chutney really is.",
    147: "The vendor knows which tea suits a first visit.",
    148: "Regular visitors know what this market is like on an ordinary weekday.",
    149: "Players at this court know how newcomers actually get a turn.",
    150: "Only the players on this court can say if there's room in the next game.",
    151: "Players at this maidan know how beginners usually join.",
    152: "Staff and regulars know which lane suits a relaxed pace here.",
    153: "Players at these tables know how turns are decided here.",
    154: "Regular runners know which loop people here use at sunrise.",
    155: "Members know how this club welcomes first-time visitors.",
    156: "Regular skaters know the unwritten rules for sharing this space.",
    157: "Current students know what an ordinary week at the college feels like.",
    158: "Members know which clubs actually keep meeting after orientation.",
    159: "Members know how welcoming the club really is to beginners.",
    160: "Students here know how study groups actually form.",
    161: "Students who've been know what people actually do at the fest.",
    162: "Guides and student volunteers know how newcomers get around this campus.",
    163: "Students here know where people actually go for lunch.",
    164: "Staff and regulars know how seat-sharing really works in this library.",
    165: "The coordinator knows what new volunteers usually do here.",
    166: "Members know how this group treats slower runners.",
    167: "The organiser knows how this group's swaps usually work.",
    168: "The organiser knows how first-timers usually take part.",
    169: "Members know what keeps people coming back to this group.",
    170: "The organiser knows how newcomers join the open sessions.",
    171: "Regular participants know what the atmosphere is really like.",
    172: "Volunteers know which items they can usually help with.",
    173: "Regular walkers know which loop people here enjoy in daylight.",
    174: "Regular visitors know what the waterfront is like on weekday mornings.",
    175: "Locals know which square feels calm for a walk.",
    176: "Regulars know how people actually spend evenings at Marine Drive.",
    177: "Residents who shop here know what they value about this market.",
    178: "Locals know which tea stall people return to for a chat.",
    179: "Regular visitors know how the garden is used when it's quiet.",
    180: "Parents at the fair know what families enjoy beyond the main stage.",
    181: "Library staff know the simplest way to register here.",
    182: "Desk staff know which counter handles first-time visitors.",
    183: "The organiser knows what first-time participants usually bring.",
    184: "The coordinator knows how new volunteers usually start.",
    185: "Regular commuters know how the queue works at this stop.",
    186: "Market workers know how first-timers find the right stall.",
    187: "Festival staff know which entrance works best when it's busy.",
    188: "The volunteer coordinator knows how first-timers can help on open days.",
    189: "Only people living in the hostels know what everyday life there feels like.",
    190: "Current or former residents know what hostel life there is really like.",
    191: "Students a year ahead remember what surprised them most.",
    192: "Employees there know what the culture is like week to week.",
    193: "Past runners know what they wish they had prepared for.",
    194: "Current students know what day-to-day life there feels like.",
    195: "Former apprentices know what learning in the workshop was really like.",
    196: "Parents living there know what raising children in Baner is like.",
    197: "Long-time residents know what they value about living there.",
    198: "Current volunteers know what a normal shift involves.",
    199: "Regular members know what the atmosphere is like on a normal day.",
    200: "People who make this commute know what it's really like day to day.",
    201: "Current students know what the studio culture is really like.",
    202: "People who moved there know what helped them settle in.",
}
